###
# Notes
###

# Images
# priximmo/rng:latest
# priximmo/hasher:latest
# priximmo/webui:latest
# priximmo/worker:latest
# redis

---
apiVersion: v1
kind: Namespace
metadata:
  name: dockercoins

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: priximmo/rng:latest
        ports:
        - containerPort: 80
          name: rng

---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  selector:
    app: rng
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: rng

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: priximmo/hasher:latest
        ports:
        - containerPort: 80
          name: hasher

---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  selector:
    app: hasher
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: hasher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dockercoins
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: priximmo/worker:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: dockercoins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: priximmo/webui:latest
        ports:
        - containerPort: 80
          name: webui

---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  selector:
    app: webui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31498
    protocol: TCP
    name: webui
  type: NodePort
