---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xrng
  name: xrng
  annotation:
    kubernetes.io/change-cause: Add configmap
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrng
  template:
    metadata:
      labels:
        app: xrng
    spec:
      containers:
      - name: xrng
        image: priximmo/rng:latest
        volumeMounts:
          - name: rng-config-volume
            mountPath: /config.yaml
            subPath: config.yaml
    volume:
      - name: xrng-config
        configMap:
          name: xrng-config
          items:
            - key: config.yaml
              path: config.yaml
