---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xrng
  name: xrng
  annotations:
    kubernetes.io/change-cause: Add configmap
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrng
  template:
    metadata:
      labels:
        app: xrng
    spec:
      containers:
      - name: xrng
        image: priximmo/rng:latest
        volumeMounts:
          - name: xrng-config-volume
            mountPath: /config.yaml
            subPath: config.yaml
      volumes:
        - name: xrng-config-volume
          configMap:
            name: xrng-config
            items:
              - key: config.yaml
                path: config.yaml
