---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rng
  name: rng
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: priximmo/rng:latest
