---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rng
  name: rng
  namespace: dockercoins
spec:
  selector:
    app: rng
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: rng
