---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xrng
  name: xrng
  namespace: dockercoins
spec:
  selector:
    app: xrng
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: xrng
