---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
  name: webui
  namespace: dockercoins
spec:
  selector:
    app: webui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31498
    protocol: TCP
    name: webui
  type: NodePort
