---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xhasher
  name: xhasher
  annotations:
    kubernetes.io/change-cause: Add configmap
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xhasher
  template:
    metadata:
      labels:
        app: xhasher
    spec:
      containers:
      - name: xhasher
        image: priximmo/hasher:1.1.0
        volumeMounts:
          - name: xhasher-config-volume
            mountPath: /config.yaml
            subPath: config.yaml
      volumes:
        - name: xhasher-config-volume
          configMap:
            name: xhasher-config
            items:
              - key: config.yaml
                path: config.yaml
