---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher
  name: hasher
  namespace: dockercoins
spec:
  selector:
    app: hasher
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: hasher
