---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xhasher
  name: xhasher
  namespace: dockercoins
spec:
  selector:
    app: xhasher
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: xhasher
