---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: dockercoins
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis